
services:
  vite-app:
    build: .
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      - ../../.:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: sh -c "npm install && npx vite serve"