
services:
  vite-app:
    build: .
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      - ../../.:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: sh -c "npm install && npx vite serve"
    
  mongodb:
    image: mongo:8.0.11
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports: 
      - 27017:27017
    volumes:
      - gamecollection:/data/db

volumes:
  gamecollection:
      driver: local